### ISSUE TITLE
Explore CLIP Model and Its Architectures

### ISSUE THREAD

**Issue by sravanigona** [UMass-Rescue/ImageSearch_CLIP#3]
**Description:** Conduct research on the CLIP model, with a specific focus on the underlying architectures, such as ViT (Vision Transformer) and ResNet. Summarize how these architectures are applied in CLIP for tasks like image and text embedding generation. Identify key differences and potential benefits of each architecture in relation to the project.

**Outcome:** A document summarizing ViT and ResNet architectures in the context of CLIP, with recommendations on their application.

**Comment by sahithi-66** [comment]
Completed research on ViT and ResNet architectures in CLIP. Document summarizes their roles in image and text embeddings, with recommendations for our project. Issue resolved.

link to full investigation: https://docs.google.com/document/d/1dWDi4RSms3p9qRrlBtXvreLUiSjo_tLzKoTlrj9QYZw/edit?usp=sharing
