### ISSUE TITLE
Create an App Info Page

### ISSUE THREAD

**Issue by sravanigona** [UMass-Rescue/ImageSearch_CLIP#83]
Develop a dedicated App Info Page that provides users with detailed information about the application, including its purpose, key features, and usage instructions. The page should be accessible through the application’s interface and should serve as a user-friendly guide for both new and experienced users. It should include sections such as:

Overview: A brief description of the app and its functionalities.
How to Use: Step-by-step instructions for performing core tasks (e.g., image ingestion, text-to-image search, etc.).

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a new route '/app_info' to provide users with detailed information about the application, including its purpose, key features, and usage instructions. The content is derived from the existing README.md file.

You can review changes in this commit: https://github.com/lkilu6456546/UMass-Rescue-ImageSearch_CLIP-83/commit/2ec59dd5de479a2759a6dc8e85f3ca87c23d84ac.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
