### ISSUE TITLE
Test the Entire Model on Unsplash Dataset for Performance Evaluation

### ISSUE THREAD

**Issue by sravanigona** [UMass-Rescue/ImageSearch_CLIP#87]
**Description**: Conduct a comprehensive evaluation of the entire image retrieval system by testing it on the Unsplash dataset. The goal is to assess the model’s performance in real-world scenarios by running it on a diverse and large-scale dataset, which contains high-quality images across various categories.

**Tasks**:
Integrate the Unsplash dataset into the image retrieval pipeline.
Ensure the model is compatible with the dataset’s structure (image formats, annotations, etc.).
Run the model on the entire Unsplash dataset to evaluate top-k retrieval performance.

**Comment by sahithi-66** [comment]
The model has been tested on the Unsplash dataset. The integration and compatibility with the dataset were ensured, and top-k retrieval performance was evaluated. The task is complete, and this issue can now be closed.
